{% set name = "stevedore" %}
{% set version = "2.0.0" %}
{% set bundle = "tar.gz" %}
{% set hash = "001e90cd704be6470d46cc9076434e2d0d566c1379187e7013eb296d3a6032d9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip
    - pbr !=2.1.0,>=2.0.0

  run:
    - python
    - pbr !=2.1.0,>=2.0.0
    - six >=1.10.0


test:
  imports:
    - stevedore
    - stevedore.named
    - stevedore.driver
    - stevedore.hook
    - stevedore.extension
    - stevedore.enabled
    - stevedore.dispatch
    - stevedore.tests

about:
  home: http://docs.openstack.org/developer/stevedore/
  license_file: LICENSE
  license: Apache 2.0
  license_family: Apache
  summary: Manage dynamic plugins for Python applications
  doc_url: http://docs.openstack.org/developer/stevedore/
  dev_url: https://git.openstack.org/cgit/openstack/stevedore

extra:
  recipe-maintainers:
    - anguslees
    - pmlandwehr
