{% set name = "stevedore" %}
{% set version = "5.1.0" %}
{% set bundle = "tar.gz" %}
{% set hash = "a54534acf9b89bc7ed264807013b505bf07f74dbe4bcfa37d32bd063870b087c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.8
    - pip
    - pbr !=2.1.0,>=2.0.0

  run:
    - python >=3.8
    - pbr !=2.1.0,>=2.0.0

test:
  imports:
    - stevedore
    - stevedore.named
    - stevedore.driver
    - stevedore.hook
    - stevedore.extension
    - stevedore.enabled
    - stevedore.dispatch
    - stevedore.tests
    - stevedore._cache
  requires:
    - pip
  commands:
    - pip check

about:
  home: http://docs.openstack.org/developer/stevedore/
  license_file: LICENSE
  license: Apache-2.0
  license_family: Apache
  summary: Manage dynamic plugins for Python applications
  doc_url: http://docs.openstack.org/developer/stevedore/
  dev_url: https://git.openstack.org/cgit/openstack/stevedore

extra:
  recipe-maintainers:
    - anguslees
    - tschoonj
